version: '3'
services:
  mtms-client-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: mtms-ng-dev
    command: npm start
    volumes:
      - '.:/app'
    ports:
      - '4200:4200'
