FROM node:12.16-alpine3.11
WORKDIR /app
COPY . /app
RUN apk add git
RUN git config --global user.email "p.oliva@memodo.de"
RUN git config --global user.name "Pablo Oliva"
# RUN npm install
RUN npm install g @angular/cli
RUN npm link @angular/cli
EXPOSE 4200
CMD ["npm", "start"]
